### ISSUE TITLE
Instead of Time headers I am getting date based messages

### ISSUE THREAD

**Issue by mpc20001** [QuickBlox/QMChatViewController-ios#101]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/QMChatViewController-ios/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QMChatViewController version*
ios 10, Quickblox iOS SDK 2.9

**Did this work before?**
No

**Expected behavior**
chatDataSource.addMessages should add my messages to the chatDataSource. 

**Actual behavior**
chatDataSource.addMessages adds my messages to the chatDataSource but also adds additional cells with Time headers added as information.

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

 ID: 583d04ed5b5f42373e0041d0			
 senderID: 19921115			
 recipientID: 0			
 dateSent: 2016-11-25 08:00:00 +0000			
 text: November 25			
 customParameters: {
    kQBDateDividerCustomParameterKey = 1;
}			
 attachments: (null)			
 delayed: 0			
 dialogID: (null)			
 read: 0			
 readIDs: (null)			
 deliveredIDs: (null)			
 markable: 0			
 createdAt: (null)			
 updatedAt: (null)

**Steps to reproduce the behavior**

**Any others comments?**
I just want to remove these cells from my chatview. Is there an easy way to do this?

**Comment by Raikerian** [comment]
Hi,

So you don't want time headers?

**Comment by mpc20001** [comment]
Yes, but I already figured out hot to remove it!

**Comment by Raikerian** [comment]
Glad to hear you have figured it out, if you have any other problems please let us know by creating a separate issue.

**Comment by dipayan92Innofied** [comment]
Hi,
Can someone suggest me how to show the day in section instead of chat cell?
Even removal of 
![screen shot 2017-03-27 at 7 35 53 pm](https://cloud.githubusercontent.com/assets/25582609/24360325/a3613898-1324-11e7-890b-6a1f65f08e3c.png)
date will also help.
