### ISSUE TITLE
QMChatSectionManager alternative

### ISSUE THREAD

**Issue by iurichiba** [QuickBlox/QMChatViewController-ios#102]
Hi, I need an alternative to QMChatSectionManager, since it's been deprecated in v0.4.
We use it in places like:

```obj-c
#pragma mark - QMChatCollectionViewDelegateFlowLayout
- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section {
    NSInteger count = [self.chatSectionManager messagesCountForSectionAtIndex:section];
    if (count > 0) [UIView animateWithDuration:0.35f animations:^{
        self.collectionView.alpha = 1.0f;
    }]; return count;
}
```

For `[self.chatDataSource messageForIndexPath:indexPath]` and some other occasions it's ok, chatDataSource works fine -- but sometimes I need `messagesCountForSectionAtIndex` or `chatSectionAtIndex`, but those aren't present in chatDataSource and don't seem to work anymore with chatSectionManager.

 **Environment details**
QMChatViewController v0.4.0.1

**Did this work before?**
Yes, before v0.4

Hope you guys can help me. Thanks :)

**Comment by iurichiba** [comment]
![tumbleweed](http://i.giphy.com/O38dU2kkQ9sWc.gif)

**Comment by Raikerian** [comment]
Hi,

I appreciate your joke, sorry for the long answer as we are having some developers on holidays recently :)

Yes, QMChatDataSource is now a complete replacement for QMChatSectionManager. It has almost everything that QMChatSeciontManager had except sections and... bugs! Yes, we have lots of bugs with the section approach, and not only bugs, section approach for something like chat is producing bad performance too.
So, answering your question about `messagesCountForSectionAtIndex ` and `chatSectionAtIndex `, the only section that is existent now is 0, there no other sections and never will be in QMChatDataSource. All messages count should be replacement for `messagesCountForSectionAtIndex ` and `0` for `chatSectionAtIndex `. If it doesn't help you, I recommend to see our updated sample chat with usage of QMChatDataSource here: https://github.com/QuickBlox/quickblox-ios-sdk
If you have some implementation that is not represented in our sample, feel free to show some parts of it so I can help you with replacements of all methods.

**Comment by iurichiba** [comment]
Hi, @Raikerian,

Haha, it was just a joke, but I'm glad you liked it, though. I know how complicated it is to keep up in December.

As for the sections problem, it's gonna be a challenge for us to refactor so much of our code that depended on these sections -- however, since it's probably gonna make it more stable, it's probably for the better.

Btw, you should really update the README ASAP, even if it means deleting a few lines and replacing them later - it'd prevent confusion for new users.

Thanks!

**Comment by Raikerian** [comment]
Yeah, we do need to update README with newest methods, thanks for pointing that out.
