### ISSUE TITLE
issue in QMChatviewcontroller example

### ISSUE THREAD

**Issue by pranaleejadhav** [QuickBlox/QMChatViewController-ios#103]
i am unable to run QMChatviewcontroller demo. get some lib error.. No issue.I created new project ,added QMChatviewcontroller through pods. Used same code from file 'DemoChatViewController' given in QMChatviewcontroller. I have just kept 2 messgaes. Plesae see the screenshot how it is looking.  Look at first message. It is coming automatically. Today header must not be included in a message. Also, why the collectionview is scrolled to bottom? I tried setting automaticallyScrollsToMostRecentMessage to NO. still there is no effect?
I installed QMChatviewcontroller using command yesterday => 
pod 'QMChatViewController'

![screen shot 2016-12-10 at 12 08 13 am](https://cloud.githubusercontent.com/assets/22271492/21060339/d2a90534-be6c-11e6-8628-5435028fadda.png)

Please check.

**Comment by Raikerian** [comment]
Hi,

Example project is working fine for me 😕 
Can you please attach any logs of the exact error you are having and any additional steps on how to reproduce it?
