### ISSUE TITLE
Store Chats in SQLite  DB

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/QMChatViewController-ios#105]
I want to store my previous chats in DB then show from there in ChatviewController.
In Which method i will get the all the messages with respect to dialog id.

I debug the Sample chat and found QBChatDatasource have all the chats but didn't confident.
Please tell me where i will get the all the message. So that i will store it for future if internet not available, show old messages from the chat.

**Kindly help me.**

**Comment by Raikerian** [comment]
Hi,

I dont really understand, are you talking about our samples? Our samples already have persistent storage, we are storing dialogs and messages in Core Data. It is implemented in our [QMServices](https://github.com/QuickBlox/q-municate-services-ios), which is included with our samples.

**Comment by ErAshu** [comment]
I want to show old messages in the chatviewcontroller even internet not available. So i want to store the messages in the Sqlite table.

**Comment by ghost** [comment]
@ErAshu Hello, as @Raikerian  already said, for your needs you can use [QMServices](https://github.com/QuickBlox/q-municate-services-ios). The main feature is inbox persistent and memory storage for messages, dialogs and users.
