### ISSUE TITLE
How do we show the typing indicator?

### ISSUE THREAD

**Issue by mpc20001** [QuickBlox/QMChatViewController-ios#107]
I saw in this doc - http://cocoadocs.org/docsets/QMChatViewController/0.2.2/Classes/QMChatViewController.html - that there is a property called showTypingIndicator but it seems to be missing in the latest build. Is there another way to show a typing indicator?

*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/QMChatViewController-ios/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QMChatViewController version*

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by ghost** [comment]
@mpc20001 We have removed this property in QMChatVC 0.3. 

You can take a look at our implementation of the [typing indicator in Q-municate](https://github.com/QuickBlox/q-municate-ios/search?utf8=%E2%9C%93&q=QMOnlineTitleView+*onlineTitleView&type=Code).
