### ISSUE TITLE
Toolbar not goes up when tapped in textview

### ISSUE THREAD

**Issue by ErAshu** [QuickBlox/QMChatViewController-ios#108]
Hi,
I am facing this issue. I have integrate QMCHATVIEWCONTROLLER in my project.
Expectation :- Inputtoolbar should go above the keyboard.

I am using cocoapod.

![simulator screen shot 07-jan-2017 10 12 25 am](https://cloud.githubusercontent.com/assets/4178384/21739485/14dd4396-d4c2-11e6-85fb-3bfe143d803a.png)

**Comment by ghost** [comment]
@ErAshu, What version of QMChatVC do you use?

**Comment by rcorin** [comment]
I also have this issue @VitaliyGuru ... not sure how to check the version?

**Comment by rcorin** [comment]
Using MBProgressHUD (0.9.2)
Using QMChatViewController (0.4.0.1)
Using QMServices (0.4.5)
Using QuickBlox (2.9)
Using SDWebImage (3.8.2)
Using SVProgressHUD (2.0.4)
Using TTTAttributedLabel (2.0.0)

**Comment by NamanVaishnav** [comment]
I've added QMChatViewController in container  and  the problem is with inputToolBar , it does not goes up when tapped in textview,
