### ISSUE TITLE
How to change the style of sending date of the message

### ISSUE THREAD

**Issue by deeplearningcj** [QuickBlox/QMChatViewController-ios#11]
I have tried with this QMChatViewController and it looks easy to use. However, in order to make it integrate into a real product, we need to customize the style of sending date of the message. Currently, the design looks not good.
I also download Q-municate in my iphone and it shows the date information elegantly. It has the day information as the header section in the chat view.
 Can you help show me how to implement similar way in QMChatViewController?

**Comment by Forsarion** [comment]
We will add this in next release of QMChatViewController.

**Comment by Forsarion** [comment]
Added in 0.3 version.
