### ISSUE TITLE
chat date like "Today" in chat cell instead of section

### ISSUE THREAD

**Issue by dipayan92Innofied** [QuickBlox/QMChatViewController-ios#110]
I am getting chat date in chat cell instead of section.How to show to the date in section instead of chat cell?There is a closed issue but he has not replied the way to do it.

Please reply as soon as possible.

![screen shot 2017-03-27 at 7 35 53 pm](https://cloud.githubusercontent.com/assets/25582609/24360473/046b59ac-1325-11e7-8089-0612ef0b0c10.png)

**Comment by ghost** [comment]
@dipayan92Innofied, You should use another cell class for date divider.
To check if the message is date divider you can use the property:

`message.isDateDividerMessage`
