### ISSUE TITLE
sectionHeaderAtIndexPath Method replacement as it's Deprecated

### ISSUE THREAD

**Issue by malavagile** [QuickBlox/QMChatViewController-ios#112]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/QMChatViewController-ios/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QMChatViewController version*
I am looking for replacement for below method as it's Deprecated in new version of quickblox.
Method :
  - (UICollectionReusableView *)collectionView:(QMChatCollectionView *)collectionView
                    sectionHeaderAtIndexPath:(NSIndexPath *)indexPath DEPRECATED_MSG_ATTRIBUTE("Deprecated in 0.4.0.")

I didn't find it anywhere. I would like to display "Today" and "Tomorrow" view in the chat controller.

**Comment by ghost** [comment]
@malavagile, You can check message for 'isDateDividerMessage'. 
```obj-c
- (Class)viewClassForItem:(QBChatMessage *)message {
    ///
    if (message.isDateDividerMessage) {
        return [Your_date_divider_cell_class class];
    }
    ///
}
```
