### ISSUE TITLE
QMCollectionView

### ISSUE THREAD

**Issue by jaipee1** [QuickBlox/QMChatViewController-ios#120]
How to get item index when i tap on a cell that contain image, i want to get this image to show in a pop up. and i using did select item at index path method but this method didn't call.

**Comment by ghost** [comment]
@jaipee1, QMChatCell has delegate `QMChatCellDelegate` with method :
`- (void)chatCellDidTapContainer:(QMChatCell *)cell;`

All you need is to adopt this protocol in your Chat View Controller and set cell.delegate = `Your Chat VC`.

```objective-c
    NSIndexPath *indexPath = [self.collectionView indexPathForCell:cell];
    QBChatMessage *message = [self.chatDataSource messageForIndexPath:indexPath];
```

**Comment by jaipee1** [comment]
Thanks for help.
