### ISSUE TITLE
QMPlaceHolderTextView pasteDelegate conflict with new pasteDelegate property in iOS 11

### ISSUE THREAD

**Issue by 1tatarchuk** [QuickBlox/QMChatViewController-ios#133]
In iOS 11 Apple introduced new pasteDelegate property of UITextView. It conflicts with pasteDelegate property of QMPlaceHolderTextView causing crash. I think it should be renamed.

https://developer.apple.com/documentation/uikit/uitextpasteconfigurationsupporting/2887494-pastedelegate

**Comment by jkmathew** [comment]
I have same issue, its crashing on iOS 10.x since I updated project to use Xcode 9.
Saying 
```
-[QMPlaceHolderTextView setPasteDelegate:]: unrecognized selector sent to instance 0x104158800
```

**Comment by ghost** [comment]
Hi @1tatarchuk,
Could you please provide steps for reproduce?

Thanks.

**Comment by jkmathew** [comment]
@Pro100Andrey ,
in my case I have dialogue list controller and chat view controller. When I go to chat view controller and come back to dialog list controller the application crashes with above message.

To be precise, its crashing on this line https://github.com/QuickBlox/QMChatViewController-ios/blob/c76569fc1dc19f4a2cc35c63a2e8dff036e67481/QMChatViewController/QMChatViewController.m#L70

**Comment by 1tatarchuk** [comment]
@Pro100Andrey @jkmathew same thing, crash when list of chats dealloc and trying to remove all delegates

**Comment by Vincent-Loi** [comment]
@Pro100Andrey Same. Any plans to fix this?

> Steps:
> 1. Tap on a chat from dialogs view
> 2. Go back to dialogs
> 3. Crashed on same line.

**Comment by tarekabdallah** [comment]
@Pro100Andrey it can be fixed by renaming the delegate (tried it). The steps to reproduce in my case:

1. Open a chat.
2. Paste anything in the textView.

Please note that this scenario was reproducible on iOS 10.3.1 and never happened on iOS 11

**Comment by ghost** [comment]
@1tatarchuk, @jkmathew, @tarekabdallah  Please check out development branch.
