### ISSUE TITLE
How to use the voice recording?

### ISSUE THREAD

**Issue by MartinSchultz** [QuickBlox/QMChatViewController-ios#138]
I wonder how I shall implement correctly the voice recording feature. I've implemented the delegate callbacks in the chat view controller and I can see the time progressing when I hold the microphone button. I also see, when I release the button, that the audio recording end event is fired. 

But how do I access then the audio file? Where is it stored? I only get as parameter the toolbar supplied. I wonder where the audio recording is happening. Any hint on this?

Thanks
Martin

**Comment by myatmin8** [comment]
same question from me.

**Comment by mobile3000** [comment]
audio recording button is not appeared.
I need your help.

**Comment by ghost** [comment]
@MartinSchultz , @CLogin , @mobile3000  Hello everyone.
fixed in the development branch. [Please check this commit](https://github.com/QuickBlox/QMChatViewController-ios/commit/30263b6314d40975a1c1dba89ef8d6576897da0e)
