### ISSUE TITLE
How to adjust the toolbar position in the ChatviewController when tabbar is hidden.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/QMChatViewController-ios#140]
Hi,
I am using Quickblox in my project. I am facing a design issue here.
I am displaying dialogs in a view controller contains tabbar. When dialog is selected it is navigating to the chat viewcontroller. chat viewcontroller is default design just displaying the profile pics and changed the navigationbar design. for hiding the tabbar in chat view controller, enabled the hide bottombar on push option in storyboard. For that option tabbar is hidden. but the input toolbar is not adjusting. please give suggestion for displaying the design correctly. Below is the screenshot.
![screen shot 2018-01-05 at 12 15 57 pm](https://user-images.githubusercontent.com/9112899/34598624-d2955922-f213-11e7-9e59-6570ed473557.png)

**Comment by Aragunz** [comment]
How did you fix this @ajay2c9 ?

**Comment by ajay2c9** [comment]
I override  "inputToolBarStartPos" method  which is used in the QMChatviewcontroller. I kept this  method in my chatViewController.

-(NSUInteger)inputToolBarStartPos {
    return 0;
}

I think this is helpfull.

**Comment by Aragunz** [comment]
Yeah but when you actually get this by pod you cant do anything unless you modify pod classes, and the property is not public to override it as i can see.

**Comment by Aragunz** [comment]
Can you please take a look at this issue it repeats in quickblox example too @Pro100Andrey. Thank you

**Comment by ajay2c9** [comment]
Hi @Aragunz,
Actually i didn't modify in the pod files. I take a ViewController with subclass as QmChatViewController. I placed "inputToolBarStartPos" method in that view controller. No Need to change in the podfile .

**Comment by Aragunz** [comment]
@ajay2c9 thank you, it didnt work for me bro, i am using swift.

**Comment by vladburlaciuc** [comment]
@objc func inputToolBarStartPos() -> Int{
        return 0;
    }
