### ISSUE TITLE
Using this sdk and facing issue.....

### ISSUE THREAD

**Issue by JittenderKumar** [QuickBlox/QMChatViewController-ios#143]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/QMChatViewController-ios/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QMChatViewController version*
iOS Version: 11
Quickblox : 2.15
QMChatViewController : Latest

**Did this work before?**
I am using first time.

**Expected behavior**
Need to show chat list.

**Actual behavior**
i have an array.
i am using this line of code to add message on chatviewcontroller.
[self.chatDataSource addMessages:messageArray];

But it is showing data wrong.
i am sharing screen shot and  also the data from json.

![simulator screen shot - iphone 6s - 2018-02-19 at 18 31 44](https://user-images.githubusercontent.com/18693089/36379057-2e597ccc-15a3-11e8-85f6-37a82b325d6d.png)

"data": [
    {
      "id": 9,
      "text": "i am fine bro....u say?",
      "is_read": 0,
      "clients_id": 31,
      "conversation_id": "14471447",
      "created_at": "2018-02-19 10:45:32",
      "created_for": 1447,
      "created_by": 1447
    },
    {
      "id": 11,
      "text": "i am fine bro....u say?",
      "is_read": 0,
      "clients_id": 31,
      "conversation_id": "14471447",
      "created_at": "2018-02-19 10:56:51",
      "created_for": 1447,
      "created_by": 1447
    },
    {
      "id": 13,
      "text": "ok",
      "is_read": 0,
      "clients_id": 31,
      "conversation_id": "14471447",
      "created_at": "2018-02-19 12:40:59",
      "created_for": 1447,
      "created_by": 1447
    },
    {
      "id": 16,
      "text": "everything is ok?",
      "is_read": 0,
      "clients_id": 31,
      "conversation_id": "13081447",
      "created_at": "2018-02-19 12:52:31",
      "created_for": 1447,
      "created_by": 1308
   }]

it is not showing these messages as these are in array.
like 0,1,2,3
it is showing 2,3,0,1
i didn't get it.

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by JittenderKumar** [comment]
Please reply.........

**Comment by ghost** [comment]
@JittenderKumar, The messages in the data source are sorted by ID and date.
