### ISSUE TITLE
Not able to remove audio recording icon 

### ISSUE THREAD

**Issue by ziad007** [QuickBlox/QMChatViewController-ios#144]
**Environment details**
*iOS version, Quickblox iOS SDK version, QMChatViewController version*

**Did this work before?**
Not sure

**Expected behavior**
I am setting self.inputToolbar.audioRecordingEnabled = false; but audio recording icon need to be show off.
 

**Actual behavior**
I am setting self.inputToolbar.audioRecordingEnabled = false; but audio recording icon is still showing

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by ghost** [comment]
Hi @ziad007, Thank you for informing us!

**Comment by ghost** [comment]
@ziad007,  🚀  QMChatViewController (0.6.3) successfully published, [changelog](https://github.com/QuickBlox/QMChatViewController-ios/releases/tag/0.6.3).

Thanks!
