### ISSUE TITLE
InputToolbar extra margin in UITabBarController when keyboard is visible

### ISSUE THREAD

**Issue by ykorshev** [QuickBlox/QMChatViewController-ios#146]
Hi everyone. I'm facing issue when try to use qmchatviewcontroller in
UITabBarController >> UINavigationController >> UIViewController >> QMChatViewController
There is an extra margin appear between keyboard and inputToolbar
![image 2018-04-12 14 10 50](https://user-images.githubusercontent.com/17659602/38656035-4f65342a-3e5b-11e8-92f4-1fbde7f8b239.jpg)

What should I do? I already override inputToolBarStartPos

**Comment by ykorshev** [comment]
Any updates?

**Comment by ghost** [comment]
Hi @ykorshev, in progress

**Comment by ghost** [comment]
Fixed v 0.6.4

**Comment by ghost** [comment]
Check https://github.com/QuickBlox/QMChatViewController-ios/tree/master/ChatExample

![simulator screen shot - iphone 6s plus - 2018-04-17 at 18 10 26](https://user-images.githubusercontent.com/1109916/38878870-a71e9d24-426a-11e8-8598-32fe02f620db.png)



![simulator screen shot - iphone 6s plus - 2018-04-17 at 18 10 32](https://user-images.githubusercontent.com/1109916/38878878-ad7d26f4-426a-11e8-8ab0-25a77e60a798.png)

**Comment by pgona** [comment]
![whatsapp image 2018-09-07 at 9 56 36 am](https://user-images.githubusercontent.com/43057007/45198625-0d664200-b285-11e8-8cfa-d960bcd199aa.jpeg)
Input text issue while on call.
