### ISSUE TITLE
Swipe back gesture freeze UI

### ISSUE THREAD

**Issue by ykorshev** [QuickBlox/QMChatViewController-ios#149]
When Keyboard is visible, swipe back gesture causes UI to run infinite loop of layout updates. App becomes unresponsible. Issue appears ONLY when keyabord is VISIBLE. Disabling interactive pop gesture recognizer of navigation controller solves this problem.

**Comment by ghost** [comment]
Hi @ykorshev, thanks for the report.

**Comment by ghost** [comment]
🚀  QMChatViewController (0.6.5) successfully published
 📅  May 2nd, 18:24
 🌎  https://cocoapods.org/pods/QMChatViewController
