### ISSUE TITLE
Audio Recording duration is not updating

### ISSUE THREAD

**Issue by ziad007** [QuickBlox/QMChatViewController-ios#154]
**Environment details**
*iOS version: 11
Quickblox iOS SDK version : 2.17.1
QMChatViewController version:  0.6.6

**Did this work before?**
Not sure

**Expected behavior**
duration audio recording should be updated

**Actual behavior**
duration audio recording not updating

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
<img width="415" alt="screen shot 2018-10-04 at 12 59 15 pm" src="https://user-images.githubusercontent.com/1684813/46467211-dcbaef00-c7d5-11e8-9108-47452275e7cd.png">

**Any others comments?**

**Comment by ziad007** [comment]
providing a value to ```func audioRecordingDuration(_ toolbar: QMInputToolbar!) -> TimeInterval``` will solve this problem

**Comment by vivekradadiya** [comment]
I'm having same issue.
Also there is no any official document and sample code for sending audio chat using this library.
If anyone had implemented the audio attachment then please help us...
