### ISSUE TITLE
Run the project.

### ISSUE THREAD

**Issue by FullStackDevCoach** [QuickBlox/QMChatViewController-ios#157]
I've just installed the pod and run the project.
But I have some issues on the project like..
1. "Could not build Objective-C module QMChatViewController" in import QMChatViewController
2. progress param Error in QMImageView.h, setImageWithURL function
3. progress param Error in QMImageLoader.h, downloadImageWithURL function

???

**Comment by romansorochak** [comment]
same issue my side.
any progress on fixing this ?

**Comment by mandeepsangwan21** [comment]
First remove the pod QMChatViewController and now install the
` pod 'SDWebImage', '~> 4.4.6'`
Then again install the `pod QMChatViewController.`
`pod QMChatViewController` has dependency on `pod 'SDWebImage', '~> 4.4.6'` and later versions of SDWebImage are throwing errors.
