### ISSUE TITLE
Update QMChatViewController to use the latest SDWebImage v5.9.0 pod.

### ISSUE THREAD

**Issue by haarj** [QuickBlox/QMChatViewController-ios#163]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/QMChatViewController-ios/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QMChatViewController version*
iOS 13.7, QB v 2.17.4

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by haarj** [comment]
What do you recommend as an alternative to this? Thanks!

**Comment by ghost** [comment]
You are most welcome. You can use our [official SDKs](https://docs.quickblox.com/docs) and [samples](https://docs.quickblox.com/docs/code-samples).
