### ISSUE TITLE
Crash when view dialog and back for some times.

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/QMChatViewController-ios#25]
1. Go to a dialog.
2. Back to list dialogs.

Repeat some times, then it crashes.

**Comment by Raikerian** [comment]
Hi!

Thank you for reporting the issue, unfortunately this is not enough to understand your issue. Could you please provide us crash log?
Also in which version of QMChatViewController you were able to reproduce this crash?

**Comment by tranngoclinh88** [comment]
I'm using version 0.3.2. I got your answer in other issue.
