### ISSUE TITLE
Handle tap in message item

### ISSUE THREAD

**Issue by thdvdev** [QuickBlox/QMChatViewController-ios#3]
Hi,
Can you show me how to handle tap action in message with picture attachment please?
 I tried collectionView:didSelectItemAtIndexPath but it never called.

Thank you.

**Comment by thiemdv** [comment]
I have to customize it myself.

**Comment by unoiatech** [comment]
Any update ? I also want to handle tap on attachment cell.

**Comment by unoiatech** [comment]
This can help you https://github.com/QuickBlox/QMChatViewController-ios/issues/120
