### ISSUE TITLE
How to maintain the container size constant whether the text is small or large.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/QMChatViewController-ios#42]
Hi,
In the chat cells  the width of the container is changed according to the text. How to maintain the constant width of the container when the text is small or large.
Please give suggestions.

**Comment by Raikerian** [comment]
Hi,

If you want to maintain cell width manually for some reason, there is a data source method for that:

``` objectivec
- (CGFloat)collectionView:(QMChatCollectionView *)collectionView minWidthAtIndexPath:(NSIndexPath *)indexPath;
```

Here is an example from our samples:
https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat/sample-chat/ViewController/ChatViewController.m#L429

**Comment by ajay2c9** [comment]
Thank you for suggestion. if adjusting the above the above method . container height is not adjusting according to the text . For how to adjust the container width and height (i.e   background of the text message).I got the container size height issue for Incoming cell for multiple lines.PLease check the Below image  second section.

![screen shot 2016-03-31 at 2 58 34 pm](https://cloud.githubusercontent.com/assets/9112899/14171867/d1a7e07e-f752-11e5-8a4f-9142b704c348.png)

Please give suggestions

**Comment by Raikerian** [comment]
@ajay2c9 please checkout our samples here, ChatViewController class should be helpful for you. It contains a lot of customisation already: https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat/sample-chat/ViewController/ChatViewController.m

If you are still having any other troubles or questions feel free to create a separate issue.
