### ISSUE TITLE
How to adjust the alignment of emojis after sending the text.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/QMChatViewController-ios#43]
Hi,
 When emojis are given after entering the text, space is displaying after emojis .how to adjust the alignment. this is occurring in the sample also . and container size is not adjusting when large text is give it comes on the other cell. below is the screenshot

![screen shot 2016-03-31 at 6 51 02 pm](https://cloud.githubusercontent.com/assets/9112899/14177156/981a7d10-f772-11e5-8ddc-478d790a3482.png)

**Comment by Raikerian** [comment]
@ajay2c9 Thank you for reporting the issue, we will investigate it.

**Comment by sertony** [comment]
@ajay2c9  maximumLineHeight = font.lineHeight in NSParagraphStyle attribute fixes this issue.

```
NSMutableParagraphStyle *paragraphStyle = [[NSParagraphStyle defaultParagraphStyle] mutableCopy];
paragraphStyle.maximumLineHeight = font.lineHeight;

NSDictionary *attributes = @{NSParagraphStyleAttributeName: paragraphStyle, ...}
NSMutableAttributedString *attrStr = [[NSMutableAttributedString alloc] initWithString:string attributes:attributes];
```

**Comment by Raikerian** [comment]
@ajay2c9 can you test your message in our latest samples and tell me result?
