### ISSUE TITLE
How to stop the jumbling and Flickering of images.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/QMChatViewController-ios#44]
Hi, 
While sending the continuous images in the chat , flickering and jumbling is occurring. please give suggestions. how to stop the flickering and jumbling.It is occurring in the chat sample too.
Thank you

**Comment by Raikerian** [comment]
Hi,

Can you give us something like a video on that flickering?

**Comment by Raikerian** [comment]
@ajay2c9 any updates on this?
