### ISSUE TITLE
Facing Transitive dependency issue while installing from Pod

### ISSUE THREAD

**Issue by Anurag15990** [QuickBlox/QMChatViewController-ios#5]
The 'Pods' target has transitive dependencies that include static binaries: (/Users/anurag/Workspace/ios-candidate/Pods/QuickBlox/Quickblox.framework)

<img width="640" alt="screen shot 2015-09-24 at 11 39 39 am" src="https://cloud.githubusercontent.com/assets/7747446/10066482/00cd7c4c-62b1-11e5-967b-c167bc109923.png">

**Comment by fstephany** [comment]
Same here with:
- CocoaPods 0.38.2
- QMChatViewController (0.2.4)
- QuickBlox (2.4.3)

My Podfile: 

```
platform :ios, "8.0"
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target "app" do
  pod 'REMenu', '~> 1.10'
  pod 'SDWebImage', '~>3.7.3'
  pod 'MBProgressHUD', '~>0.9.1'
  pod 'DTCoreText', '~> 1.6.16'
  pod 'SwiftyJSON', '~> 2.3.0'
  pod 'FBSDKLoginKit', '~> 4.6.0'
  # pod 'QuickBlox', '~> 2.4.3'
  pod 'QMChatViewController', '~> 0.2.4'
end
```

**Comment by Forsarion** [comment]
Hi!

We are aware of this issue, unfortunately we don't have Quickblox built as a dynamic framework. Mainly because we still need to support iOS 7.
So, removing option 'use_frameworks!' from your Podfile will fix described issue.

We will try to find out more appropriate solution in nearest future.

**Comment by jbmaxwell** [comment]
Any news on this problem? I'm working with RxSwift/RxCocoa, which are dynamic frameworks...

**Comment by Forsarion** [comment]
Unfortunately - no news. We are supporting iOS 7 so we can't upload dynamic framework to CocoaPods.
We are thinking on dropping iOS 7...

**Comment by jbmaxwell** [comment]
Thanks Andrey,

That’s fine. We were able to rebuild our app for static frameworks. 

However, if we try to pull the calls from your pod file into the pod file for our project, the download fails (“could not read remote repository”). (Actually, if we do an “rm -rf Pods” in your directory, then install/update it also fails—so something’s wrong with the pod file.) We managed to get the download working by using https paths, but that doesn’t actually download the files you use in your project—they seem to be different versions, and the project doesn't compile anymore. Any help appreciated.

Thanks,

J.

**Comment by obernal** [comment]
I'm having this exact same problem. Any news on dropping iOS 7 support? I'm using a bunch of swift frameworks and cannot get rid of `use_frameworks!` option

**Comment by jbmaxwell** [comment]
@obernal: In the end our solution was to download all the files and use local paths in our pod file. Indeed, dropping iOS 7 (or at least getting a dynamic version) would be ideal for us too.

**Comment by obernal** [comment]
@jbmaxwell thanks for the reply. Could you share a bit more about your setup? Was it just downloading QMChatViewController or Quickblox too?
