### ISSUE TITLE
13 error in QMServicesDevelopment.framework

### ISSUE THREAD

**Issue by RonakPatel07** [QuickBlox/QMChatViewController-ios#53]
ld: warning: directory not found for option '-F/Users/slk039/Desktop/QuickBlox_VideoCalling_Timer/Quickblox_Videocall_Swift/Pods/../../Framework'
ld: warning: directory not found for option '-F/Users/slk039/Desktop/QuickBlox_VideoCalling_Timer/Quickblox_Videocall_Swift/Pods/../External'

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_QBChat", referenced from:
      objc-class-ref in QMChatService+Bolts.o
      objc-class-ref in QMChatService.o
      objc-class-ref in QMContactListService+Bolts.o
      objc-class-ref in QMContactListService.o
      objc-class-ref in QMUsersService.o
  "_OBJC_CLASS_$_QBChatAttachment", referenced from:
      objc-class-ref in CDAttachment.o
      objc-class-ref in QMChatAttachmentService.o
  "_OBJC_CLASS_$_QBChatDialog", referenced from:
      objc-class-ref in CDDialog.o
      objc-class-ref in QBChatMessage+QMCustomParameters.o
      objc-class-ref in QMChatService.o
  "_OBJC_CLASS_$_QBChatMessage", referenced from:
      objc-class-ref in CDMessage.o
      l_OBJC_$_CATEGORY_QBChatMessage_$_QMCustomParameters in QBChatMessage+QMCustomParameters.o
      l_OBJC_$_CATEGORY_QBChatMessage_$_TextEncoding in QBChatMessage+TextEncoding.o
      objc-class-ref in QMChatService.o
  "_OBJC_CLASS_$_QBContactListItem", referenced from:
      objc-class-ref in CDContactListItem.o
  "_OBJC_CLASS_$_QBGeneralResponsePage", referenced from:
      objc-class-ref in QMUsersService.o
  "_OBJC_CLASS_$_QBMulticastDelegate", referenced from:
      objc-class-ref in QMAuthService.o
      objc-class-ref in QMChatService.o
      objc-class-ref in QMContactListService.o
      objc-class-ref in QMUsersService.o
  "_OBJC_CLASS_$_QBRequest", referenced from:
      objc-class-ref in QMAuthService.o
      objc-class-ref in QMChatAttachmentService.o
      objc-class-ref in QMChatService+Bolts.o
      objc-class-ref in QMChatService.o
      objc-class-ref in QMUsersService.o
  "_OBJC_CLASS_$_QBResponsePage", referenced from:
      objc-class-ref in QMChatService+Bolts.o
      objc-class-ref in QMChatService.o
  "_OBJC_CLASS_$_QBSession", referenced from:
      objc-class-ref in QMAuthService.o
      objc-class-ref in QMChatService.o
      objc-class-ref in QMServicesManager.o
  "_OBJC_CLASS_$_QBSettings", referenced from:
      objc-class-ref in QMChatService+Bolts.o
      objc-class-ref in QMChatService.o
  "_OBJC_CLASS_$_QBUUser", referenced from:
      objc-class-ref in CDUser.o
      l_OBJC_$_CATEGORY_QBUUser_$_QMAssociatedObject in QBUUser+CustomData.o
      l_OBJC_$_CATEGORY_QBUUser_$_CustomData in QBUUser+CustomData.o
      objc-class-ref in QMChatService.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RonakPatel07** [comment]
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '7244eaf609797a5dc5ec6d28dc2b284633b03a1f'

pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => 'ab56ac143bb770e76409a027bfb38de582d728aa'

---

pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '5bb608405c89bbb3b0189a4e188098f27c2af72a'

pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => '84e55c43f028589d9f6304b1224bcdc62926b619'

i tried with both but both gives 13 error.
how to solve this ?

Thanks in advance!!

**Comment by ghost** [comment]
Hi @RonakPatel07, the listed above errors mean that you didn't add Quickblox.framework.
To clarify it could you please show your podfile?
You can add this framework using CocoaPods or manually. 
For more further explanation, please refer to [this](http://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework) documentation.

**Comment by RonakPatel07** [comment]
Hi @VitaliyGuru  

pod 'QuickBlox'
pod 'Quickblox-WebRTC'

# pod 'QMChatViewController'

#Production pod
pod 'QMCVDevelopment', :git => 'git@github.com:QuickBlox/QMChatViewController-ios.git', :commit => '5bb608405c89bbb3b0189a4e188098f27c2af72a'

#For development pods
#pod 'QMCVDevelopment', :path =>`` '../../QMChatViewController-ios/'

#Production pod
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => '84e55c43f028589d9f6304b1224bcdc62926b619'

I Added latest version of quickblox and webrtc with pod installtion.
also i checked with both with added of 'QMChatViewController' and without this.

but this 13 error as it is.

**Comment by Raikerian** [comment]
Hi @RonakPatel07 

Can you provide sample project with this error?

**Comment by RonakPatel07** [comment]
ok bro @Raikerian 

i will send you dropbox link via email

**Comment by Raikerian** [comment]
@RonakPatel07 Unfortunately you cannot use Quickblox frameworks in pods with `use_frameworks!` param. Please refer to: https://github.com/QuickBlox/QMChatViewController-ios/issues/5

Remove this flag or install Quickblox using our [manual installation guide](http://quickblox.com/developers/IOS-how-to-connect-Quickblox-framework#Framework).

**Comment by RonakPatel07** [comment]
Hi, @Raikerian 

that 13 error are gone with manual installation but new error generate.

**Quickblox/Quickblox.h  file not found**

i already created .pch file and added in prefix header also.

**Comment by Raikerian** [comment]
Follow our manual installation guide for QMServices here: https://github.com/QuickBlox/q-municate-services-ios#2-using-an-xcode-subproject

**Comment by RonakPatel07** [comment]
Hi, @Raikerian 

My Demo Link :: https://www.dropbox.com/s/d0re7qcsy1bf2jp/QB_Demo_Manually_Installtion.zip?dl=0

Please help me how to fix it.

**Comment by Raikerian** [comment]
@RonakPatel07 were you able to fix it?
