### ISSUE TITLE
QMChatViewController using as is

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/QMChatViewController-ios#54]
Hey guys, I looked trough your demo project for swift, my question is can I use QMChatViewController without writing or overriding it. So I mean that in your demo project you've added a lot of sources and for now after migration from previous version to new one it's hard to migrate for me all code. at least that we don't have any section manager before and I also has my custom object that handle for me authorization and mange quick block dialogs features.

thanks

**Comment by matrosovDev** [comment]
seems I've done with your demo code. on more question, can we share recorded video as we share photo now.

**Comment by Raikerian** [comment]
Hi,

There is no feature to share a video yet. We have plans to add it, but there is no any ETA yet. You can implement it by yourself for now.

**Comment by matrosovDev** [comment]
ok got it, thanks!

**Comment by Raikerian** [comment]
In order to receive updates on our product feel free to follow our [blog here](http://quickblox.com/blog/).
