### ISSUE TITLE
App crashing when a video is attached in quickblox chat room

### ISSUE THREAD

**Issue by ppreeti** [QuickBlox/QMChatViewController-ios#55]
//here is problem
- (QBChatMessage *)messageForIndexPath:(NSIndexPath *)indexPath 
  {
      if (indexPath.item == NSNotFound)
      {
          return nil;
      }
      QMChatSection *currentSection = self.chatSections[indexPath.section];
      return currentSection.messages[indexPath.item];
  }

/*
Exception is
**\* Assertion failure in -[QMChatCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /SourceCache/UIKit_Sim/UIKit-3347.44.2/UICollectionView.m:4056  

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (2) must be equal to the number of sections contained in the collection view before the update (1), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted).'

 */

**Comment by Raikerian** [comment]
Hi,

We do not have video attach support in our chat view controller for now. You can implement it yourself by subclassing from QMChatCell. Even though I don't think your crash is related to this. Please add Exception breakpoints and try to catch the exact line where it is crashes. If its same as you linked, look at debugger queue and see lines of code that were called before this.

**Comment by Raikerian** [comment]
@ppreeti any updates on this?
