### ISSUE TITLE
How to customised or else use my own nib for tool bar in ChatViewController using Quickblox?

### ISSUE THREAD

**Issue by WillsAtIOS** [QuickBlox/QMChatViewController-ios#57]
I want to use a custom tool bar for my chat view controller instead of existing tool bar available in sample-chat-IOS app.

And I don't want to disturb exiting QMToolbarContentView.nib and QMToolbarContentView.h and QMToolbarContentView.m files. Below Image 1 is the existing one. and Image 2 is what I want.

So which is the best to load my own tool bar nib. Is it possible or I should modify the existing one ?

And I found one method but don't know weather this will work ?

Please go through this stack over flow link to see the images and complete question. 

[http://stackoverflow.com/questions/37215391/how-to-customised-or-else-use-my-own-nib-for-tool-bar-in-chatviewcontroller-usin]

**Environment details**
_iOS version, Quickblox iOS SDK version, QMChatViewController version_

**Comment by Raikerian** [comment]
Duplicate, see https://github.com/QuickBlox/quickblox-ios-sdk/issues/468
