### ISSUE TITLE
QMImageView setting image with url bug

### ISSUE THREAD

**Issue by fenomenar9** [QuickBlox/QMChatViewController-ios#61]
When setting image from url via setImageWithURL: then setting it from an image (via Camera or Library)

we will not be able to change the image via setImageWithURL: anymore. 

I think that this is caused by the following test in setImageWithURL: method:

if ([url isEqual:self.url]) {
        return;
    }

**Comment by Raikerian** [comment]
Hi,

Yes, url should be different. How one url can contain different images? Please explain your case in a little bit more details.

**Comment by ghost** [comment]
@fenomenar9 
Any updates?

**Comment by fenomenar9** [comment]
@VitaliyGuru 
I have just commented this "if" block
if ([url isEqual:self.url]) {
return;
}
