### ISSUE TITLE
Crash after receive message

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/QMChatViewController-ios#62]
Sometimes, I got this crash.
Here is my log.

**Logs**
_Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))_
<img width="1000" alt="screen shot 2016-05-25 at 11 05 08 am" src="https://cloud.githubusercontent.com/assets/1511264/15528022/1ae3d288-226a-11e6-86f5-fe2cb0311cb4.png">

**Comment by Raikerian** [comment]
Hi,

Unfortunately this is not enough to understand your issue. We will need some steps to reproduce it.
