### ISSUE TITLE
How to display messages from top to bottom?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/QMChatViewController-ios#75]
Currently, messages displayed from bottom to top. How to display them from top to bottom?

**Comment by Raikerian** [comment]
Hi,

Our QMChatViewController is transformed upside down. There is no any public API to undo that. However you can always Fork from it and remove any transformation done within it.

**Comment by tranngoclinh88** [comment]
@Raikerian 
Can you please tell me where I can change it in QMChatViewController?

**Comment by Raikerian** [comment]
Search project for ".transform" keyword. Comment that line.
