### ISSUE TITLE
Is there any possibility to implement the QMChatSectionManager in UiViewController with delegate methods.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/QMChatViewController-ios#76]
Is there any possibilities to use the QMChatSectionManager in UIViewController and how delegate methods are used in that ViewController without using the  QMChatViewController. The it is implemented in UitableView and with custom cell design.

**Comment by Raikerian** [comment]
@ajay2c9 Hi, QMChatSectionManager was designed to be used with QMChatViewController. It is basically data source for UICollectionViewController. While you want to use UITableView, our data source will not match your requirements unfortunately.
