### ISSUE TITLE
Pod file is not in a wroking state

### ISSUE THREAD

**Issue by voodoo-rocks** [QuickBlox/QMChatViewController-ios#92]
Analyzing dependencies
[!] The dependency `QuickBlox (= 2.5)` is not used in any concrete target.
The dependency `QMCVDevelopment (from`../`)` is not used in any concrete target.

Add targets to pod file like this

target 'QMChatViewControllerExample' do
pod 'QuickBlox', '2.5'
pod 'QMCVDevelopment', :path => '../'
end

**Comment by ghost** [comment]
@voodoo-mobile , You should replace `pod 'QMCVDevelopment', :path => '../'` with `pod 'QMChatViewController'`
