### ISSUE TITLE
Pods are not installed correctly

### ISSUE THREAD

**Issue by voodoo-rocks** [QuickBlox/QMChatViewController-ios#93]
I just ran pod install and the project (workspace) looks like that (see screenshot). I can not run it or even see source files (only in .xproject)

![screen shot 2016-09-29 at 12 04 45](https://cloud.githubusercontent.com/assets/9930603/18941633/6a449eea-8645-11e6-994d-bf7560e1a2e7.png)
_Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/QMChatViewController-ios/issues)_

**Environment details**
_iOS version, Quickblox iOS SDK version, QMChatViewController version_

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
_Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by ghost** [comment]
Hello, could you show me your podfile?

**Comment by ghost** [comment]
Hi @voodoo-mobile, Any updates?
