### ISSUE TITLE
How to show Full name instead of senderID for each message?

### ISSUE THREAD

**Issue by phiren** [QuickBlox/QMChatViewController-ios#95]
Hi,

How to show full name instead of senderId for each message?

Thanks
Hiren

**Comment by ghost** [comment]
Hello, @phiren 
Could you expand a little bit on expected and actual result?

**Comment by phiren** [comment]
HI @VitaliyGuru 

This demo shows sender 's ID on top label of each message in group chat. In my case, we want the name of the User to be shown instead of the sender ID. Showing sender id seems meaning less (@12121212 )

**Comment by phiren** [comment]
Hi @VitaliyGuru, Any  update here?

**Comment by ghost** [comment]
@phiren , in method implementation 
[\- (NSAttributedString *)topLabelAttributedStringForItem:(QBChatMessage *)messageItem {...}](https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat/sample-chat/ViewController/ChatViewController.m?L#L401-L432)  for group dialog we get `QBUUser *messageSender`. Instance of QBUUser has property `fullName`, so you can use it.

**Comment by ghost** [comment]
If you're not using [QMServices](https://github.com/QuickBlox/q-municate-services-ios) you can get user by ID and then get his `fullName`.

```
    __block NSString *userFullName = nil;
    [QBRequest userWithID:[messageItem senderID] successBlock:^(QBResponse * _Nonnull response, QBUUser * _Nullable user) {
        userFullName = user.fullName;
    } errorBlock:^(QBResponse * _Nonnull response) {
    }];
```

**Comment by rcorin** [comment]
Hello, I've a PublicGroup dialog and use QMServices, but still messageSender is nil. What could be the problem?
@VitaliyGuru 
Thanks!

**Comment by ghost** [comment]
@rcorin, Please create a separate issue and add this information.

**Comment by jkmathew** [comment]
@VitaliyGuru ,
What to do if the user is not present in inMemoryCache?
I found a way to load users with  `QBRequest.users(withIDs:......` so that I can load users with groups  occupant ids. 
Can I save it back to in memory storage or will it load automatically?
is this good way to do this?
