### ISSUE TITLE
Crashing when loading nib of QMChatViewController from subclassed viewcontroller

### ISSUE THREAD

**Issue by mpc20001** [QuickBlox/QMChatViewController-ios#97]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/QMChatViewController-ios/issues)*
 
**Environment details**
*iOS version, Quickblox iOS SDK version, QMChatViewController version*
I'm using this with swift 2.3 xcode 8 - I'm using the latest version of Quickblox and QMChatViewController

**Did this work before?**
No

**Expected behavior**
Can't load QMChatViewController

**Actual behavior**
I get a crash everytime when I try to load the nib.

`'NSInvalidArgumentException', reason: 'NSLayoutConstraint for <QMInputToolbar: 0x7f970a6cb750; baseClass = UIToolbar; frame = (0 524; 320 44); opaque = NO; autoresize = RM+BM; layer = <CALayer: 0x600000023120>>: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs.'`

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
https://gist.github.com/anonymous/5232001f339ff0d2cb5edddd303d993e

**Steps to reproduce the behavior**

running on swift
**Any others comments?**
no

**Comment by Raikerian** [comment]
Hi,

We are currently working on updated chat controller in development branch and are going to release it soon. Can you try chat controller from development branch and hit us up if anything is working good?

**Comment by mpc20001** [comment]
Sure.

**Comment by mpc20001** [comment]
I tried version 0.4 but I am still getting the same crash. Please advise.

**Comment by mpc20001** [comment]
I know what the problem is. I can't install via cocoa pods - I'm not
allowed by my project manager to use cocoa pods and it seems compiling it
without cocoa pods causes an error. Any thoughts on how to get around this?

**Comment by Raikerian** [comment]
Can you setup a test project (clean one) with issue being reproducible and attach it here?

**Comment by mpc20001** [comment]
[QBTestProject.zip](https://github.com/QuickBlox/QMChatViewController-ios/files/585591/QBTestProject.zip)

Sure.

**Comment by Raikerian** [comment]
Is there a test project with version 0.4 of chat controller?

**Comment by mpc20001** [comment]
[QBTestProject_updated.zip](https://github.com/QuickBlox/QMChatViewController-ios/files/586260/QBTestProject_updated.zip)
Here you go. Same crash occurs.

**Comment by Raikerian** [comment]
I'm currently working on this issue and will post update soon.

**Comment by mpc20001** [comment]
Great! Thanks so much.

**Comment by Raikerian** [comment]
Please update to 0.4.0.1, should be fixed now.

**Comment by mpc20001** [comment]
fixed.
